### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlenJakob** [AlenJakob/e-comerce#13]
1. [x] Przeładowanie podczas przechodzenia między stronami 

9. [x]  routing do strony danego produktu ( strona główna produktu )
4. [x] przycisk scroll do góry strony **14**
2. [x]  breadcrumbsy i aktywny status dla danej podstrony  **13** 
8. [ ]  Checkout podstrona koszyka ( designy gotowe  figma ) **19** ( **in progress** )
9. [x] Routing na produkt z poziomu koszyka **21**
3. [ ]   Nawigacja podąża za użytkownikiem podczas scrollowania **15**
5. [ ] toast/popup - informujący że produkt został dodany **16**
6. [ ] Stopka dla stron **17**
7. [ ] Mobilna Wersja dla całej strony ( wszystkie obszary ) **18**
8. [x] favi icon **20**
9.  [ ] "Go to payment" step 2 ( step 1 is in shopping cart )
10. [ ] "Confirm payment" step 3

**Comment by AlenJakob** [comment]
14: breadcrumbsy- przejscie na dany produkt powoduje zmiane url np 

**collection** na **/id** przez co breadcrumbsy mają struturę `Home / collection` a po przejściu na produkt `Home / 20 `

**Comment by AlenJakob** [comment]
TODO: in /#13:breadcrumbs - clean code
